-dontwarn com.google.errorprone.**
-dontwarn org.apache.commons.**
-dontwarn com.google.code.rome.android.**
-dontwarn org.simpleframework.**
-dontwarn com.fasterxml.jackson.**
-dontwarn org.codehaus.**
-dontwarn org.slf4j.**
-keep class com.ashomok.ocrme.**
-dontshrink
-dontoptimize
-dontpreverify

